# replace "elevated-surge-287013" in the three targets below with your actual project(s)
apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: pop-stats-pipeline
description: pop-stats application delivery pipeline
serialPipeline:
 stages:
 - targetId: test
 - targetId: staging
   profiles:
   - staging
 - targetId: prod
   profiles:
   - prod
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: test
description: test cluster
gke:
  cluster: projects/jfrog-marketplace-demo/locations/us-central1/clusters/testclusters
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: staging
description: staging cluster
gke:
  cluster: projects/jfrog-marketplace-demo/locations/us-central1/clusters/stagingclusters
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
description: prod cluster
requireApproval: true
gke:
  cluster: projects/jfrog-marketplace-demo/locations/us-central1/clusters/prodclusters
