# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml
#

substitutions:
  _JFROG_SERVER_NAME: swampup.jfrog.io
  _JFROG_REPO_NAME: swampup-docker-local
  _JFROG_CLI_VERSION: 2.11.0
  _JFROG_USER: abambah@google.com
  _PIPELINE_REGION: us-central1
  _JFROG_API_KEY: <api key>


steps:
  # Build the Cloud Builder Image that includes JFrog CLI
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'jfrog-cli-docker'
    args:
      - 'build'
      - '--build-arg=BASE_IMAGE=gcr.io/cloud-builders/npm:node-14.10.0'
      - '--tag=gcr.io/$PROJECT_ID/npm/${_JFROG_CLI_VERSION}'
      - '--tag=${_JFROG_SERVER_NAME}/${_JFROG_REPO_NAME}/jfrog-cli:${_JFROG_CLI_VERSION}'
      - '.'
    wait_for: [ '-' ]

  # Tag a default builder version.
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'jfrog-cli-docker'
    args:
      - 'tag'
      - '${_JFROG_SERVER_NAME}/${_JFROG_REPO_NAME}/jfrog-cli:${_JFROG_CLI_VERSION}'
      - '${_JFROG_SERVER_NAME}/${_JFROG_REPO_NAME}/jfrog-cli'

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: [ '-c', 'docker login ${_JFROG_SERVER_NAME} -u ${_JFROG_USER} -p $$JFROG_ACCESS_TOKEN' ]
    dir: 'jfrog-cli-docker'
    secretEnv: [ 'JFROG_ACCESS_TOKEN' ]


  # Docker Push the image to artifactiry
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', '${_JFROG_SERVER_NAME}/${_JFROG_REPO_NAME}/jfrog-cli:${_JFROG_CLI_VERSION}' ]
    dir: 'jfrog-cli-docker'
    secretEnv: [ 'JFROG_ACCESS_TOKEN' ]



      #images:
      #- '${_JFROG_SERVER_NAME}/${_JFROG_REPO_NAME}/jfrog-cli:${_JFROG_CLI_VERSION}'
      #- '${_JFROG_SERVER_NAME}/${_JFROG_REPO_NAME}/jfrog-cli'
      #tags: ['cloud-builders-community']

availableSecrets:
    secretManager:
    - versionName: projects/$PROJECT_ID/secrets/jfrog-access-token/versions/2
      env: 'JFROG_ACCESS_TOKEN'